---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: result
  namespace: instavote
spec:
  chart:
    spec:
      chart: ./deploy/charts/result
      sourceRef:
        kind: GitRepository
        name: instavote
  install: {}
  interval: 10m0s
  targetNamespace: default
