apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  minReadySeconds: 20
  selector:
    matchLabels:
      app: vote
  replicas: 5
  template:
    metadata:
      labels:
        app: vote
    spec:
        containers:
        - image: schoolofdevops/vote:v3
          name: vote
          envFrom:
            - configMapRef:
               name: vote-options
               optional: true
                  
