apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
- worker.yaml
replicas:
  - name: vote
    count: 8
images:
  - name: schoolofdevops/vote
    newTag: v5 
namespace: instavote
commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "sre@example.com"

configMapGenerator:
  - name: vote-options
    envs:
      -  options.env
