apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: woerk
  name: worker
spec:
  minReadySeconds: 20
  replicas: 5
  template:
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker
