apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  minReadySeconds: 20
  selector:
    matchLabels:
      app: worker
  replicas: 2
  template:
    metadata:
      labels:
        app: worker
    spec:
        containers:
        - image: schoolofdevops/worker:latest
          name: worker
